### PR TITLE
Update Invoke-Environment.ps1

### PR DESCRIPTION
**Pull request by nanoric**
Quote command.

### CODE REVIEW

**Comment by nightroman** [comment]
Thank you but this change is not quite right.

Example: `1.cmd`

```cmd
@echo off
echo param1 %1
echo param2 %2
```

This works before you change:

```
Invoke-Environment.ps1 '1.cmd arg1 arg2' -Output
```

and gives:

```
param1 arg1
param2 arg2
```

With the suggested change it fails:

```
'"1.cmd arg1 arg2"' is not recognized as an internal or external command,
operable program or batch file.
```

---

In other words, you should add all required quotes in your `Command` parameters yourself, see the help comments example.

**Comment by nightroman** [comment]
I agree that some improvements are needed in order to invoke a batch file in paths with spaces and with arguments with spaces and maybe with special characters with escaping. But this is not that straightforward. `cmd /c` is pain...

**Comment by nanoric** [comment]
Yes, you are right, I neglected the arguments.

**Comment by nightroman** [comment]
@nanoric 
I created a related issue. It's time to make some improvements. I had some pain myself, even being the author :)

**Comment by nightroman** [comment]
And it's done. Use the new parameter `File` with optional `Arguments`.

**Pull request closed without merging**
