### PR TITLE
Modify Watch-Directory

### PR DESCRIPTION
**Pull request by deevus**
- Add ability to pass an array of directories
- Add ability to provide an exclusion pattern
- Cleanup pre-existing events before registration

Now creates an array of FileSystemWatcher to support watching of
multiple directories without complex regular expressions and to limit the
amount of tree traversal.

### CODE REVIEW

**Comment by nightroman** [comment]
I like the first two additions. Why do you think we need "Cleanup pre-existing events before registration"?

I do not use `ForEach-Object` and its alias `%`. But I can rework this myself, do not worry.

**Comment by deevus** [comment]
I had issues where there was a lingering event that for some reason weren't cleaned up in the `finally` block. Is there a situation where the `finally` block doesn't execute?

**Comment by nightroman** [comment]
This issue has to be investigated, understood, and resolved, if possible. Clearning evens as proposed is not quite right. `finally` should always execute. I do not quite like `-ErrorAction SilentlyContinue` there, btw. Why is it? Does not it exactly hides why events left not removed?

I will post a slightly reworked script shortly. Then I will think of all this.

**Comment by nightroman** [comment]
Currently removal of not existing events generates a lot of errors on starting. `-ErrorAction SilentlyContinue` is not a good solution. I will remove it until I know why it is needed. In this case I will make it to work without errors.

**Comment by nightroman** [comment]
Found it. This is not correct

```
    $events |% {
        Unregister-Event -SourceIdentifier $_.Name -ErrorAction SilentlyContinue
    }
```

Instead we should collect IDs and use them for `Unregister-Event`. The update is coming shortly.

**Comment by nightroman** [comment]
Done, try the updated script. I also renamed `Pattern` to `Include`, as far as we added `Exclude`, they make a pair now. And I released PowerShelf v1.6.0 with the new script included.

**Pull request merged**
